const boardData={notice:[['안내','교육활동 침해 사안 신고 및 지원 신청 안내','2026.09.08'],['공지','교원 법률지원단 상담 이용 방법','2026.09.03'],['안내','교육활동보호센터 심리상담 연계 안내','2026.08.27'],['공지','피해교원 치료비 지원 신청서류 안내','2026.08.19']],policy:[['정책','교육활동 보호를 위한 학교 민원 대응 체계 안내','2026.09.02'],['법령','교원지위법 주요 내용과 사안처리 유의사항','2026.08.25'],['정책','지역교권보호위원회 운영 안내','2026.08.11'],['자료','피해교원 보호조치 업무 안내','2026.07.30']],training:[['온라인','관리자를 위한 교육활동 침해 사안처리 연수','2026.09.10'],['집합','학교 교권보호 담당자 실무 연수','2026.09.05'],['온라인','교원을 위한 악성민원 대응 및 기록 방법','2026.08.28'],['자료','교육활동 보호 예방교육 수업자료','2026.08.14']]};
const dialogData={emergency:['긴급 사안 대응 순서','<ol><li>위험한 장소에서 벗어나고 주변에 도움을 요청합니다.</li><li>학교 관리자에게 즉시 알리고 침해행위자와 분리합니다.</li><li>폭행·협박 등 긴급한 위험은 112에 신고합니다.</li><li>상황이 안정된 뒤 시간·장소·내용과 증거를 기록합니다.</li><li>교육활동보호센터를 통해 법률·심리 지원을 요청합니다.</li></ol><p>이 화면은 안내용입니다. 실제 긴급상황에서는 학교와 관계기관의 지시에 따라주세요.</p>'],check:['내 상황 확인하기','<ul><li><strong>수업 방해·반복 불응:</strong> 발생 일시와 내용을 기록하고 관리자와 공유하세요.</li><li><strong>모욕·명예훼손·반복 민원:</strong> 학교 공식 민원창구로 전환하고 상담을 요청하세요.</li><li><strong>폭행·협박·성희롱:</strong> 즉시 분리와 안전 확보를 우선하고 관계기관에 신고하세요.</li></ul>'],legal:['법률상담 안내','<p>교육활동 침해와 관련한 초기 법률상담, 의견서 작성, 수사·소송 절차 안내를 받을 수 있습니다.</p><ul><li>사안 발생 일시와 경위를 시간순으로 정리</li><li>문자, 녹취, 사진 등 관련 자료 보관</li><li>학교 관리자 또는 관할 교육활동보호센터에 상담 요청</li></ul>'],care:['심리·치료 지원','<p>사건 직후의 심리상담부터 전문 치료, 복귀 후 회복 지원까지 지역 교육청의 지원 내용을 확인할 수 있습니다.</p><ul><li>전문 상담기관 연계</li><li>진료·치료비 지원 가능 여부 확인</li><li>특별휴가와 학교 복귀 지원 상담</li></ul>'],process:['단계별 세부내용','<ol><li><strong>신고:</strong> 구두 또는 서면으로 관리자에게 알립니다.</li><li><strong>보호:</strong> 즉시 분리, 특별휴가, 심리상담 등 필요한 조치를 요청합니다.</li><li><strong>조사:</strong> 관할 교육지원청이 사실관계와 의견을 확인합니다.</li><li><strong>심의:</strong> 지역교권보호위원회가 침해 여부와 조치를 심의합니다.</li><li><strong>회복:</strong> 법률·심리·치료 및 학교 복귀 지원을 연계합니다.</li></ol>']};
const boardList=document.querySelector('#board-list');function renderBoard(type){boardList.innerHTML=boardData[type].map(([category,title,date])=>`<a href="#"><b>${category}</b><span>${title}</span><time>${date}</time></a>`).join('')}renderBoard('notice');
document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(item=>{item.classList.toggle('active',item===button);item.setAttribute('aria-selected',item===button?'true':'false')});renderBoard(button.dataset.tab)}));
const dialog=document.querySelector('#info-dialog'),dialogContent=document.querySelector('#dialog-content');document.querySelectorAll('[data-dialog]').forEach(button=>button.addEventListener('click',()=>{const[title,content]=dialogData[button.dataset.dialog];dialogContent.innerHTML=`<h2>${title}</h2>${content}`;dialog.showModal()}));document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
const toast=document.querySelector('#toast');function showToast(message){toast.textContent=message;toast.classList.add('show');window.setTimeout(()=>toast.classList.remove('show'),2200)}document.querySelectorAll('[data-download]').forEach(button=>button.addEventListener('click',()=>showToast(`${button.dataset.download}는 시안용 자료입니다.`)));
document.querySelector('#site-search').addEventListener('submit',event=>{event.preventDefault();const keyword=document.querySelector('#search-input').value.trim();if(!keyword)return showToast('검색어를 입력해주세요.');showToast(`‘${keyword}’ 검색 결과는 시안에서 제공되지 않습니다.`)});document.querySelectorAll('.keywords button').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#search-input').value=button.textContent;document.querySelector('#site-search').requestSubmit()}));
document.querySelector('#region-form').addEventListener('submit',event=>{event.preventDefault();const region=document.querySelector('#region').value;document.querySelector('#region-result').textContent=region?`${region} 교육활동보호센터의 상세 연락처를 연결할 수 있습니다. (시안)`:'시·도교육청을 선택해주세요.'});
document.querySelector('#font-up').addEventListener('click',event=>{document.body.classList.toggle('large-text');event.currentTarget.textContent=document.body.classList.contains('large-text')?'글자 기본':'글자 크게'});
const menuButton=document.querySelector('.menu-button'),navigation=document.querySelector('.main-nav');menuButton.addEventListener('click',()=>{const open=navigation.classList.toggle('open');menuButton.setAttribute('aria-expanded',open?'true':'false');menuButton.textContent=open?'×':'☰'});navigation.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navigation.classList.remove('open');menuButton.setAttribute('aria-expanded','false');menuButton.textContent='☰'}));

const cycleData={
  prevention:{number:'0단계',title:'사전예방',description:'사건이 발생하기 전에 위험징후를 발견하고, 교사가 개인 연락처로 민원을 감당하지 않도록 학교 차원의 예방체계를 마련합니다.',owner:'학교 관리자 · 교육지원청 · 교육활동보호센터',actions:[['실태조사','학기 중반마다 보호 체감도, 반복 민원, 수업 방해 경험을 익명으로 확인합니다.'],['위험징후 기록','반복 불응·수업 방해·부당 간섭을 사건화 이전부터 기록하고 관리자와 공유합니다.'],['민원창구 일원화','학교 대표번호와 공식 온라인 창구로 민원을 받아 교사 개인에게 직접 전달되지 않도록 합니다.'],['예방교육','교원·학생·보호자에게 교육활동 침해 유형과 대응 절차를 정기적으로 안내합니다.']],next:'위험징후가 반복되거나 침해가 발생하면 사안발생 단계로 즉시 전환'},
  incident:{number:'1단계',title:'사안발생',description:'피해교원의 진술과 안전을 먼저 확인하고, 심각도와 긴급성에 따라 1~3등급으로 분류해 필요한 보호조치를 시작합니다.',owner:'학교 관리자 · 교육지원청 사안 담당자',actions:[['즉시 보고','교사는 관리자에게 알리고, 학교는 필요한 경우 교육지원청과 관계기관에 보고합니다.'],['안전 확보','중대 사안은 사실관계 판단보다 침해행위자 분리와 피해교원의 신체·정신적 안전을 우선합니다.'],['사안 기록','일시·장소·내용·목격자·관련 자료를 기록하되 피해교원의 반복 진술 부담을 줄입니다.'],['등급 판단','초기 징후, 명백한 침해 의심, 중대·긴급 침해의 3단계 기준으로 지원 수준을 결정합니다.']],next:'판단된 피해등급에 따라 법률·심리·행정 지원을 차등 연계'},
  support:{number:'2단계',title:'법률·심리·행정 통합지원',description:'2단계부터 전문상담을 기본 연계하고, 3단계에서는 전담 변호사·전문치료·케이스매니저가 동시에 개입합니다.',owner:'케이스매니저 · 변호사 · 전문상담사',actions:[['법률지원','초기 상담, 신고서·의견서 작성, 교보위 검토부터 수사·소송까지 같은 담당자가 지원합니다.'],['심리지원','초기 심리상태를 평가하고 상담, 전문심리치료, 의료기관을 피해 수준에 따라 연결합니다.'],['행정지원','통합 사건번호를 부여하고 교보위·공제·보험·치료비 신청과 증빙 준비를 일괄 지원합니다.'],['정보 공유','담당자가 동일 사건정보를 공유해 중복 진술과 중복 신청을 최소화합니다.']],next:'회복상태와 학교 여건을 확인해 피해교원이 주도하는 복귀계획 수립'},
  return:{number:'3단계',title:'학교복귀',description:'복귀를 단순한 출근이 아닌 준비–적응–안정화 과정으로 보고, 피해교원이 업무와 접촉 범위를 직접 선택하도록 지원합니다.',owner:'피해교원 주도 · 학교 조율 · 케이스매니저 지원',actions:[['복귀 전 2~4주','복귀설계서 작성, 동일·타 학급 또는 비담임 선택, 위험요소와 지원인력을 사전에 점검합니다.'],['복귀 직후','수업부터 부분적으로 시작하고 행정·담임 업무는 보류할 수 있으며 침해행위자와 직접 대면을 지양합니다.'],['복귀 후 3개월','격주 관리자 면담과 월 1회 피드백을 통해 업무속도·접촉범위를 교사 결정에 따라 조정합니다.'],['선택권 보장','관계회복·상담 프로그램 거부권과 사건 종결 이후 지원 재개 요청권을 보장합니다.']],next:'사건 종결 직후 재발 위험도를 평가하고 3~6개월 사후관리 시작'},
  recurrence:{number:'4단계',title:'재발방지',description:'위험도 평가, 맞춤형 사후관리, 재발 시 기관 강화 대응을 끊기지 않는 하나의 관리 과정으로 운영합니다.',owner:'사후관리 담당자 · 학교 · 교육지원청',actions:[['위험도 평가','심각성, 반복 가능성, 학생·보호자 태도를 종합해 매우 높음·높음·보통·낮음으로 분류합니다.'],['3~6개월 관리','기본 3개월, 고위험은 6개월 이상 안전·심리 상태와 추가 민원·침해 여부를 확인합니다.'],['기관 중심 대응','반복 민원은 교사가 아닌 학교·교육지원청의 공식 창구가 직접 대응합니다.'],['재발 시 강화','즉시 교육지원청 보고, 분리·출입 제한·전문기관 연계 등 보호조치를 강화하고 기록을 다음 평가에 반영합니다.']],next:'안정화 후에도 동일 사건번호를 유지해 필요할 때 지원을 다시 요청 가능'}
};

function renderCycle(key){const item=cycleData[key];document.querySelectorAll('[data-cycle]').forEach(button=>{const active=button.dataset.cycle===key;button.classList.toggle('active',active);button.setAttribute('aria-selected',active?'true':'false')});document.querySelector('#cycle-detail').innerHTML=`<div class="cycle-summary"><span class="step-label">${item.number}</span><h3>${item.title}</h3><p>${item.description}</p><span class="owner"><b>주요 담당</b>${item.owner}</span></div><div class="cycle-actions"><h4>이 단계에서 제공하는 지원</h4><div class="action-list">${item.actions.map((action,index)=>`<div><b>${index+1}</b><p><strong>${action[0]}</strong><span>${action[1]}</span></p></div>`).join('')}</div><div class="next-step"><b>다음 연결</b> ${item.next}</div></div>`}
document.querySelectorAll('[data-cycle]').forEach(button=>button.addEventListener('click',()=>renderCycle(button.dataset.cycle)));renderCycle('prevention');

const levelData={
  1:{label:'1단계 · 관찰과 기록',title:'초기 침해·위험 징후',description:'교권침해로 확대되기 전에 반복 여부를 확인하고 학교 안에서 조기에 관리합니다.',examples:'수업 중 반복적 방해, 생활지도 반복 불응, 경미한 언어적 무례, 단발성 민원·갈등',legal:['온라인·전화 법률정보 안내','전문가 의무 개입 없음'],care:['교원이 원하는 경우 상담 경로 안내','상담 참여 여부는 교원이 결정'],admin:['사안 기록 및 관리자 공유','케이스매니저 미배정, 반복 여부 모니터링'],principle:'전문가 개입 전 기록 기반을 만들고, 반복되거나 악화되면 즉시 2단계로 전환합니다.'},
  2:{label:'2단계 · 기본지원',title:'명백한 교육활동 침해 의심',description:'학교 차원의 공식 대응으로 전환하고 법률·심리 전문가와 케이스매니저를 기본 연계합니다.',examples:'수업 진행이 어려운 반복 방해, 모욕·명예훼손성 발언, 지속적 악성민원, 정당한 교육활동에 대한 반복 간섭',legal:['변호사 초기상담 1회 이상 연계','신고서·의견서 작성과 교보위 신청 검토'],care:['전문상담사 배정 및 초기 심리상태 평가','결과에 따라 상담 연장 또는 의료기관 연계'],admin:['통합 사건번호와 간이 케이스매니저 배정','담당자 정보 공유, 민원창구 일원화'],principle:'2단계부터 법률·심리 상담을 기본 개입으로 전환해 피해교원이 혼자 절차를 판단하지 않도록 합니다.'},
  3:{label:'3단계 · 최대지원',title:'중대·긴급 교육활동 침해',description:'피해교원의 안전을 최우선으로 확보하고 법률·심리·행정지원이 동시에 작동합니다.',examples:'폭행·상해·협박, 성희롱·성폭력성 사안, 심각한 명예훼손·무고, 불법 촬영·녹음·합성물 유포, 교육활동 지속이 불가능한 악성민원',legal:['전담 변호사 1:1 배치','경찰·검찰 조사 동행, 소송비·공제 동시 신청'],care:['전문심리치료·의료기관 즉시 연계','특별휴가·병가 안내, 복귀 전후 장기 모니터링'],admin:['전담 케이스매니저 원스톱 지원','증빙·신청 일괄 지원, 재발방지까지 동일 담당'],principle:'사실관계 심의가 끝나기 전이라도 즉시 분리하고, 필요한 외부기관과 최대 수준의 보호를 먼저 연결합니다.'}
};
function renderLevel(key){const item=levelData[key];document.querySelectorAll('[data-level]').forEach(button=>{const active=button.dataset.level===String(key);button.classList.toggle('active',active);button.setAttribute('aria-selected',active?'true':'false')});const column=(title,items)=>`<div class="support-column"><strong>${title}</strong><ul>${items.map(item=>`<li>${item}</li>`).join('')}</ul></div>`;document.querySelector('#level-detail').innerHTML=`<div class="level-overview"><div><span>${item.label}</span><h3>${item.title}</h3><p>${item.description}</p></div><div class="example-box"><strong>대표적인 상황</strong><span>${item.examples}</span></div></div><div class="support-table">${column('법률지원',item.legal)}${column('심리지원',item.care)}${column('행정지원',item.admin)}</div><div class="level-principle"><strong>대응 원칙</strong> ${item.principle}</div>`}
document.querySelectorAll('[data-level]').forEach(button=>button.addEventListener('click',()=>renderLevel(button.dataset.level)));renderLevel(1);
